#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: 2026 Mono Technologies Inc.

USE_PROCD=1
START=95
STOP=10

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/verso
	procd_set_param env VERSO_ADDR=:8080 VERSO_ALLOWED_HOSTS=127.0.0.1,172.20.0.10,10.0.0.232
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
