// SPDX-License-Identifier: GPL-2.0-only
// SPDX-FileCopyrightText: 2026 Mono Technologies Inc.

//! What /etc/config/firewall can hold, read out of firewall4's own parser.
//!
//! GENERATED — `cargo run --bin vocabulary -- <path to fw4.uc> --write`.
//! Do not edit: the next extraction would drop the edit, and the point of the
//! file is that it says what firewall4 says rather than what we believe.
//!
//! A difference against this file is news to read, not a thing to apply. The
//! extractor prints the difference and writes nothing unless told to.

use verso_plugin::vocabulary::{
    Cardinality, OptionSpec, Provenance, SectionVocabulary, Support, Vocabulary,
};

/// FIREWALL is every option firewall4 parses, by section type.
pub const FIREWALL: Vocabulary = Vocabulary {
    config: "firewall",
    provenance: Provenance::Extracted {
        upstream: "firewall4",
        version: "2025.03.17~b6e51575",
        sha256: "148ded17db6a8984e97875c8e60ed7e4ab4c475fbd84a31bba6b543190b4e524",
        extractor: "fw4-vocabulary v1",
    },
    sections: SECTIONS,
};

const SECTIONS: &[SectionVocabulary] = &[
    SectionVocabulary {
        kind: "defaults",
        options: DEFAULTS_OPTIONS,
    },
    SectionVocabulary {
        kind: "zone",
        options: ZONE_OPTIONS,
    },
    SectionVocabulary {
        kind: "forwarding",
        options: FORWARDING_OPTIONS,
    },
    SectionVocabulary {
        kind: "rule",
        options: RULE_OPTIONS,
    },
    SectionVocabulary {
        kind: "redirect",
        options: REDIRECT_OPTIONS,
    },
    SectionVocabulary {
        kind: "nat",
        options: NAT_OPTIONS,
    },
    SectionVocabulary {
        kind: "include",
        options: INCLUDE_OPTIONS,
    },
    SectionVocabulary {
        kind: "ipset",
        options: IPSET_OPTIONS,
    },
];

const DEFAULTS_OPTIONS: &[OptionSpec] = &[
    OptionSpec {
        key: "input",
        datatype: "policy",
        default: Some("drop"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "output",
        datatype: "policy",
        default: Some("drop"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "forward",
        datatype: "policy",
        default: Some("drop"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "drop_invalid",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "tcp_reject_code",
        datatype: "reject_code",
        default: Some("tcp-reset"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "any_reject_code",
        datatype: "reject_code",
        default: Some("port-unreachable"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "syn_flood",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "synflood_protect",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "synflood_rate",
        datatype: "limit",
        default: Some("25/second"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "synflood_burst",
        datatype: "int",
        default: Some("50"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "tcp_syncookies",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "tcp_ecn",
        datatype: "int",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "tcp_window_scaling",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "accept_redirects",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "accept_source_route",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "auto_helper",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "custom_chains",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "flow_offloading",
        datatype: "bool",
        default: Some("0"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "flow_offloading_hw",
        datatype: "bool",
        default: Some("0"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "auto_includes",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
];

const ZONE_OPTIONS: &[OptionSpec] = &[
    OptionSpec {
        key: "enabled",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "name",
        datatype: "identifier",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "family",
        datatype: "family",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "network",
        datatype: "device",
        default: None,
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "device",
        datatype: "device",
        default: None,
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "subnet",
        datatype: "network",
        default: None,
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "input",
        datatype: "policy",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "output",
        datatype: "policy",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "forward",
        datatype: "policy",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "masq",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "masq_allow_invalid",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "masq_src",
        datatype: "network",
        default: None,
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "masq_dest",
        datatype: "network",
        default: None,
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "extra",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "extra_src",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "extra_dest",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "mtu_fix",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "custom_chains",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "log",
        datatype: "int",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "log_limit",
        datatype: "limit",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "auto_helper",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "helper",
        datatype: "cthelper",
        default: None,
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "counter",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
];

const FORWARDING_OPTIONS: &[OptionSpec] = &[
    OptionSpec {
        key: "enabled",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "name",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "family",
        datatype: "family",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "src",
        datatype: "zone_ref",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "dest",
        datatype: "zone_ref",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
];

const RULE_OPTIONS: &[OptionSpec] = &[
    OptionSpec {
        key: "enabled",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "name",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "_name",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Deprecated,
    },
    OptionSpec {
        key: "family",
        datatype: "family",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "src",
        datatype: "zone_ref",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "dest",
        datatype: "zone_ref",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "device",
        datatype: "device",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: false,
        support: Support::Supported,
    },
    OptionSpec {
        key: "direction",
        datatype: "direction",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "ipset",
        datatype: "setmatch",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "helper",
        datatype: "cthelper",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "set_helper",
        datatype: "cthelper",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: false,
        support: Support::Supported,
    },
    OptionSpec {
        key: "proto",
        datatype: "protocol",
        default: Some("tcpudp"),
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "src_ip",
        datatype: "network",
        default: None,
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "src_mac",
        datatype: "mac",
        default: None,
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "src_port",
        datatype: "port",
        default: None,
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "dest_ip",
        datatype: "network",
        default: None,
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "dest_port",
        datatype: "port",
        default: None,
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "icmp_type",
        datatype: "icmptype",
        default: None,
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "extra",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "limit",
        datatype: "limit",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "limit_burst",
        datatype: "int",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "utc_time",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "start_date",
        datatype: "date",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "stop_date",
        datatype: "date",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "start_time",
        datatype: "time",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "stop_time",
        datatype: "time",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "weekdays",
        datatype: "weekdays",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "monthdays",
        datatype: "monthdays",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "mark",
        datatype: "mark",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "set_mark",
        datatype: "mark",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: false,
        support: Support::Supported,
    },
    OptionSpec {
        key: "set_xmark",
        datatype: "mark",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: false,
        support: Support::Supported,
    },
    OptionSpec {
        key: "dscp",
        datatype: "dscp",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "set_dscp",
        datatype: "dscp",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: false,
        support: Support::Supported,
    },
    OptionSpec {
        key: "counter",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "log",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "log_limit",
        datatype: "limit",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "target",
        datatype: "target",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
];

const REDIRECT_OPTIONS: &[OptionSpec] = &[
    OptionSpec {
        key: "enabled",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "name",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "_name",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Deprecated,
    },
    OptionSpec {
        key: "family",
        datatype: "family",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "src",
        datatype: "zone_ref",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "dest",
        datatype: "zone_ref",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "ipset",
        datatype: "setmatch",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "helper",
        datatype: "cthelper",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: false,
        support: Support::Supported,
    },
    OptionSpec {
        key: "proto",
        datatype: "protocol",
        default: Some("tcpudp"),
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "src_ip",
        datatype: "network",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "src_mac",
        datatype: "mac",
        default: None,
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "src_port",
        datatype: "port",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "src_dip",
        datatype: "network",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "src_dport",
        datatype: "port",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "dest_ip",
        datatype: "network",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "dest_port",
        datatype: "port",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "extra",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "limit",
        datatype: "limit",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "limit_burst",
        datatype: "int",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "utc_time",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "start_date",
        datatype: "date",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "stop_date",
        datatype: "date",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "start_time",
        datatype: "time",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "stop_time",
        datatype: "time",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "weekdays",
        datatype: "weekdays",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "monthdays",
        datatype: "monthdays",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "mark",
        datatype: "mark",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "reflection",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "reflection_src",
        datatype: "reflection_source",
        default: Some("internal"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "reflection_zone",
        datatype: "zone_ref",
        default: None,
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "counter",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "log",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "log_limit",
        datatype: "limit",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "target",
        datatype: "target",
        default: Some("dnat"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
];

const NAT_OPTIONS: &[OptionSpec] = &[
    OptionSpec {
        key: "enabled",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "name",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "family",
        datatype: "family",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "src",
        datatype: "zone_ref",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "device",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "ipset",
        datatype: "setmatch",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "proto",
        datatype: "protocol",
        default: Some("all"),
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "src_ip",
        datatype: "network",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "src_port",
        datatype: "port",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "snat_ip",
        datatype: "network",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: false,
        support: Support::Supported,
    },
    OptionSpec {
        key: "snat_port",
        datatype: "port",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: false,
        support: Support::Supported,
    },
    OptionSpec {
        key: "dest_ip",
        datatype: "network",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "dest_port",
        datatype: "port",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "extra",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "limit",
        datatype: "limit",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "limit_burst",
        datatype: "int",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "connlimit_ports",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "utc_time",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "start_date",
        datatype: "date",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "stop_date",
        datatype: "date",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "start_time",
        datatype: "time",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "stop_time",
        datatype: "time",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "weekdays",
        datatype: "weekdays",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "monthdays",
        datatype: "monthdays",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "mark",
        datatype: "mark",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "counter",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "log",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "target",
        datatype: "target",
        default: Some("masquerade"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
];

const INCLUDE_OPTIONS: &[OptionSpec] = &[
    OptionSpec {
        key: "enabled",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "path",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "type",
        datatype: "includetype",
        default: Some("script"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "family",
        datatype: "family",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "reload",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "position",
        datatype: "includeposition",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "chain",
        datatype: "identifier",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
];

const IPSET_OPTIONS: &[OptionSpec] = &[
    OptionSpec {
        key: "enabled",
        datatype: "bool",
        default: Some("1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "reload_set",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "counters",
        datatype: "bool",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "comment",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "name",
        datatype: "identifier",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "family",
        datatype: "family",
        default: Some("4"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "storage",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "match",
        datatype: "ipsettype",
        default: None,
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "iprange",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "portrange",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "netmask",
        datatype: "int",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "maxelem",
        datatype: "int",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "hashsize",
        datatype: "int",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "timeout",
        datatype: "int",
        default: Some("-1"),
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "external",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Unsupported,
    },
    OptionSpec {
        key: "entry",
        datatype: "string",
        default: None,
        cardinality: Cardinality::List,
        invertible: true,
        support: Support::Supported,
    },
    OptionSpec {
        key: "loadfile",
        datatype: "string",
        default: None,
        cardinality: Cardinality::Scalar,
        invertible: true,
        support: Support::Supported,
    },
];
